// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsuariosColumns holds the columns for the "usuarios" table.
	UsuariosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// UsuariosTable holds the schema information for the "usuarios" table.
	UsuariosTable = &schema.Table{
		Name:       "usuarios",
		Columns:    UsuariosColumns,
		PrimaryKey: []*schema.Column{UsuariosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsuariosTable,
	}
)

func init() {
}
