// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"fiberent/ent/migrate"

	"fiberent/ent/usuario"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Usuario is the client for interacting with the Usuario builders.
	Usuario *UsuarioClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Usuario = NewUsuarioClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Usuario: NewUsuarioClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Usuario: NewUsuarioClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Usuario.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Usuario.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Usuario.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *UsuarioMutation:
		return c.Usuario.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// UsuarioClient is a client for the Usuario schema.
type UsuarioClient struct {
	config
}

// NewUsuarioClient returns a client for the Usuario from the given config.
func NewUsuarioClient(c config) *UsuarioClient {
	return &UsuarioClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usuario.Hooks(f(g(h())))`.
func (c *UsuarioClient) Use(hooks ...Hook) {
	c.hooks.Usuario = append(c.hooks.Usuario, hooks...)
}

// Use adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usuario.Intercept(f(g(h())))`.
func (c *UsuarioClient) Intercept(interceptors ...Interceptor) {
	c.inters.Usuario = append(c.inters.Usuario, interceptors...)
}

// Create returns a builder for creating a Usuario entity.
func (c *UsuarioClient) Create() *UsuarioCreate {
	mutation := newUsuarioMutation(c.config, OpCreate)
	return &UsuarioCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Usuario entities.
func (c *UsuarioClient) CreateBulk(builders ...*UsuarioCreate) *UsuarioCreateBulk {
	return &UsuarioCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Usuario.
func (c *UsuarioClient) Update() *UsuarioUpdate {
	mutation := newUsuarioMutation(c.config, OpUpdate)
	return &UsuarioUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UsuarioClient) UpdateOne(u *Usuario) *UsuarioUpdateOne {
	mutation := newUsuarioMutation(c.config, OpUpdateOne, withUsuario(u))
	return &UsuarioUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UsuarioClient) UpdateOneID(id int) *UsuarioUpdateOne {
	mutation := newUsuarioMutation(c.config, OpUpdateOne, withUsuarioID(id))
	return &UsuarioUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Usuario.
func (c *UsuarioClient) Delete() *UsuarioDelete {
	mutation := newUsuarioMutation(c.config, OpDelete)
	return &UsuarioDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UsuarioClient) DeleteOne(u *Usuario) *UsuarioDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UsuarioClient) DeleteOneID(id int) *UsuarioDeleteOne {
	builder := c.Delete().Where(usuario.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UsuarioDeleteOne{builder}
}

// Query returns a query builder for Usuario.
func (c *UsuarioClient) Query() *UsuarioQuery {
	return &UsuarioQuery{
		config: c.config,
		inters: c.Interceptors(),
	}
}

// Get returns a Usuario entity by its id.
func (c *UsuarioClient) Get(ctx context.Context, id int) (*Usuario, error) {
	return c.Query().Where(usuario.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UsuarioClient) GetX(ctx context.Context, id int) *Usuario {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UsuarioClient) Hooks() []Hook {
	return c.hooks.Usuario
}

// Interceptors returns the client interceptors.
func (c *UsuarioClient) Interceptors() []Interceptor {
	return c.inters.Usuario
}

func (c *UsuarioClient) mutate(ctx context.Context, m *UsuarioMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UsuarioCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UsuarioUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UsuarioUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UsuarioDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Usuario mutation op: %q", m.Op())
	}
}
