// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fiberent/ent/usuario"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsuarioCreate is the builder for creating a Usuario entity.
type UsuarioCreate struct {
	config
	mutation *UsuarioMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (uc *UsuarioCreate) SetUsername(s string) *UsuarioCreate {
	uc.mutation.SetUsername(s)
	return uc
}

// SetEmail sets the "email" field.
func (uc *UsuarioCreate) SetEmail(s string) *UsuarioCreate {
	uc.mutation.SetEmail(s)
	return uc
}

// SetPassword sets the "password" field.
func (uc *UsuarioCreate) SetPassword(s string) *UsuarioCreate {
	uc.mutation.SetPassword(s)
	return uc
}

// Mutation returns the UsuarioMutation object of the builder.
func (uc *UsuarioCreate) Mutation() *UsuarioMutation {
	return uc.mutation
}

// Save creates the Usuario in the database.
func (uc *UsuarioCreate) Save(ctx context.Context) (*Usuario, error) {
	return withHooks[*Usuario, UsuarioMutation](ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UsuarioCreate) SaveX(ctx context.Context) *Usuario {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *UsuarioCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *UsuarioCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *UsuarioCreate) check() error {
	if _, ok := uc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Usuario.username"`)}
	}
	if _, ok := uc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Usuario.email"`)}
	}
	if _, ok := uc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Usuario.password"`)}
	}
	return nil
}

func (uc *UsuarioCreate) sqlSave(ctx context.Context) (*Usuario, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *UsuarioCreate) createSpec() (*Usuario, *sqlgraph.CreateSpec) {
	var (
		_node = &Usuario{config: uc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: usuario.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usuario.FieldID,
			},
		}
	)
	if value, ok := uc.mutation.Username(); ok {
		_spec.SetField(usuario.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := uc.mutation.Email(); ok {
		_spec.SetField(usuario.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := uc.mutation.Password(); ok {
		_spec.SetField(usuario.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	return _node, _spec
}

// UsuarioCreateBulk is the builder for creating many Usuario entities in bulk.
type UsuarioCreateBulk struct {
	config
	builders []*UsuarioCreate
}

// Save creates the Usuario entities in the database.
func (ucb *UsuarioCreateBulk) Save(ctx context.Context) ([]*Usuario, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*Usuario, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsuarioMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *UsuarioCreateBulk) SaveX(ctx context.Context) []*Usuario {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *UsuarioCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *UsuarioCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
