// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fiberent/ent/predicate"
	"fiberent/ent/usuario"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsuarioDelete is the builder for deleting a Usuario entity.
type UsuarioDelete struct {
	config
	hooks    []Hook
	mutation *UsuarioMutation
}

// Where appends a list predicates to the UsuarioDelete builder.
func (ud *UsuarioDelete) Where(ps ...predicate.Usuario) *UsuarioDelete {
	ud.mutation.Where(ps...)
	return ud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ud *UsuarioDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, UsuarioMutation](ctx, ud.sqlExec, ud.mutation, ud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ud *UsuarioDelete) ExecX(ctx context.Context) int {
	n, err := ud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ud *UsuarioDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usuario.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usuario.FieldID,
			},
		},
	}
	if ps := ud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ud.mutation.done = true
	return affected, err
}

// UsuarioDeleteOne is the builder for deleting a single Usuario entity.
type UsuarioDeleteOne struct {
	ud *UsuarioDelete
}

// Exec executes the deletion query.
func (udo *UsuarioDeleteOne) Exec(ctx context.Context) error {
	n, err := udo.ud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usuario.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (udo *UsuarioDeleteOne) ExecX(ctx context.Context) {
	udo.ud.ExecX(ctx)
}
