// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fiberent/ent/predicate"
	"fiberent/ent/usuario"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsuarioQuery is the builder for querying Usuario entities.
type UsuarioQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.Usuario
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UsuarioQuery builder.
func (uq *UsuarioQuery) Where(ps ...predicate.Usuario) *UsuarioQuery {
	uq.predicates = append(uq.predicates, ps...)
	return uq
}

// Limit the number of records to be returned by this query.
func (uq *UsuarioQuery) Limit(limit int) *UsuarioQuery {
	uq.limit = &limit
	return uq
}

// Offset to start from.
func (uq *UsuarioQuery) Offset(offset int) *UsuarioQuery {
	uq.offset = &offset
	return uq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uq *UsuarioQuery) Unique(unique bool) *UsuarioQuery {
	uq.unique = &unique
	return uq
}

// Order specifies how the records should be ordered.
func (uq *UsuarioQuery) Order(o ...OrderFunc) *UsuarioQuery {
	uq.order = append(uq.order, o...)
	return uq
}

// First returns the first Usuario entity from the query.
// Returns a *NotFoundError when no Usuario was found.
func (uq *UsuarioQuery) First(ctx context.Context) (*Usuario, error) {
	nodes, err := uq.Limit(1).All(newQueryContext(ctx, TypeUsuario, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usuario.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uq *UsuarioQuery) FirstX(ctx context.Context) *Usuario {
	node, err := uq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Usuario ID from the query.
// Returns a *NotFoundError when no Usuario ID was found.
func (uq *UsuarioQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uq.Limit(1).IDs(newQueryContext(ctx, TypeUsuario, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usuario.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uq *UsuarioQuery) FirstIDX(ctx context.Context) int {
	id, err := uq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Usuario entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Usuario entity is found.
// Returns a *NotFoundError when no Usuario entities are found.
func (uq *UsuarioQuery) Only(ctx context.Context) (*Usuario, error) {
	nodes, err := uq.Limit(2).All(newQueryContext(ctx, TypeUsuario, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usuario.Label}
	default:
		return nil, &NotSingularError{usuario.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uq *UsuarioQuery) OnlyX(ctx context.Context) *Usuario {
	node, err := uq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Usuario ID in the query.
// Returns a *NotSingularError when more than one Usuario ID is found.
// Returns a *NotFoundError when no entities are found.
func (uq *UsuarioQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uq.Limit(2).IDs(newQueryContext(ctx, TypeUsuario, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usuario.Label}
	default:
		err = &NotSingularError{usuario.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uq *UsuarioQuery) OnlyIDX(ctx context.Context) int {
	id, err := uq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Usuarios.
func (uq *UsuarioQuery) All(ctx context.Context) ([]*Usuario, error) {
	ctx = newQueryContext(ctx, TypeUsuario, "All")
	if err := uq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Usuario, *UsuarioQuery]()
	return withInterceptors[[]*Usuario](ctx, uq, qr, uq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uq *UsuarioQuery) AllX(ctx context.Context) []*Usuario {
	nodes, err := uq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Usuario IDs.
func (uq *UsuarioQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = newQueryContext(ctx, TypeUsuario, "IDs")
	if err := uq.Select(usuario.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uq *UsuarioQuery) IDsX(ctx context.Context) []int {
	ids, err := uq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uq *UsuarioQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeUsuario, "Count")
	if err := uq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uq, querierCount[*UsuarioQuery](), uq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uq *UsuarioQuery) CountX(ctx context.Context) int {
	count, err := uq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uq *UsuarioQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeUsuario, "Exist")
	switch _, err := uq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uq *UsuarioQuery) ExistX(ctx context.Context) bool {
	exist, err := uq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UsuarioQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uq *UsuarioQuery) Clone() *UsuarioQuery {
	if uq == nil {
		return nil
	}
	return &UsuarioQuery{
		config:     uq.config,
		limit:      uq.limit,
		offset:     uq.offset,
		order:      append([]OrderFunc{}, uq.order...),
		inters:     append([]Interceptor{}, uq.inters...),
		predicates: append([]predicate.Usuario{}, uq.predicates...),
		// clone intermediate query.
		sql:    uq.sql.Clone(),
		path:   uq.path,
		unique: uq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Usuario.Query().
//		GroupBy(usuario.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uq *UsuarioQuery) GroupBy(field string, fields ...string) *UsuarioGroupBy {
	uq.fields = append([]string{field}, fields...)
	grbuild := &UsuarioGroupBy{build: uq}
	grbuild.flds = &uq.fields
	grbuild.label = usuario.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.Usuario.Query().
//		Select(usuario.FieldUsername).
//		Scan(ctx, &v)
func (uq *UsuarioQuery) Select(fields ...string) *UsuarioSelect {
	uq.fields = append(uq.fields, fields...)
	sbuild := &UsuarioSelect{UsuarioQuery: uq}
	sbuild.label = usuario.Label
	sbuild.flds, sbuild.scan = &uq.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UsuarioSelect configured with the given aggregations.
func (uq *UsuarioQuery) Aggregate(fns ...AggregateFunc) *UsuarioSelect {
	return uq.Select().Aggregate(fns...)
}

func (uq *UsuarioQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uq); err != nil {
				return err
			}
		}
	}
	for _, f := range uq.fields {
		if !usuario.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uq.path != nil {
		prev, err := uq.path(ctx)
		if err != nil {
			return err
		}
		uq.sql = prev
	}
	return nil
}

func (uq *UsuarioQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Usuario, error) {
	var (
		nodes = []*Usuario{}
		_spec = uq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Usuario).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Usuario{config: uq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uq *UsuarioQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uq.querySpec()
	_spec.Node.Columns = uq.fields
	if len(uq.fields) > 0 {
		_spec.Unique = uq.unique != nil && *uq.unique
	}
	return sqlgraph.CountNodes(ctx, uq.driver, _spec)
}

func (uq *UsuarioQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usuario.Table,
			Columns: usuario.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usuario.FieldID,
			},
		},
		From:   uq.sql,
		Unique: true,
	}
	if unique := uq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usuario.FieldID)
		for i := range fields {
			if fields[i] != usuario.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uq *UsuarioQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uq.driver.Dialect())
	t1 := builder.Table(usuario.Table)
	columns := uq.fields
	if len(columns) == 0 {
		columns = usuario.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uq.sql != nil {
		selector = uq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uq.unique != nil && *uq.unique {
		selector.Distinct()
	}
	for _, p := range uq.predicates {
		p(selector)
	}
	for _, p := range uq.order {
		p(selector)
	}
	if offset := uq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UsuarioGroupBy is the group-by builder for Usuario entities.
type UsuarioGroupBy struct {
	selector
	build *UsuarioQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ugb *UsuarioGroupBy) Aggregate(fns ...AggregateFunc) *UsuarioGroupBy {
	ugb.fns = append(ugb.fns, fns...)
	return ugb
}

// Scan applies the selector query and scans the result into the given value.
func (ugb *UsuarioGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeUsuario, "GroupBy")
	if err := ugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsuarioQuery, *UsuarioGroupBy](ctx, ugb.build, ugb, ugb.build.inters, v)
}

func (ugb *UsuarioGroupBy) sqlScan(ctx context.Context, root *UsuarioQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ugb.fns))
	for _, fn := range ugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ugb.flds)+len(ugb.fns))
		for _, f := range *ugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UsuarioSelect is the builder for selecting fields of Usuario entities.
type UsuarioSelect struct {
	*UsuarioQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (us *UsuarioSelect) Aggregate(fns ...AggregateFunc) *UsuarioSelect {
	us.fns = append(us.fns, fns...)
	return us
}

// Scan applies the selector query and scans the result into the given value.
func (us *UsuarioSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeUsuario, "Select")
	if err := us.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsuarioQuery, *UsuarioSelect](ctx, us.UsuarioQuery, us, us.inters, v)
}

func (us *UsuarioSelect) sqlScan(ctx context.Context, root *UsuarioQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(us.fns))
	for _, fn := range us.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*us.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := us.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
